name: Deploy to Azure Web App

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  AZURE_WEBAPP_NAME: ipcwebsite   # exact App Service name in Azure

jobs:
  deploy:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Stage site files
        shell: pwsh
        run: |
          New-Item -ItemType Directory -Path site | Out-Null
          robocopy . site /E /XD .git .github site PrecompiledWeb /XF *.sln
          if ($LASTEXITCODE -ge 8) { exit 1 } else { exit 0 }

      - name: Azure login (OIDC)
        uses: azure/login@v2
        with:
          #client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_BC5FB212EAC14DF1AC14A3DFE1E5D154 }}
          client-id: ${{ secrets.IPC_APPREG_CLIENT_ID_NOT_OBJECT }}
          #client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_594F24BFE7174CC6AF60E6C9D05C6F08 }}
          #tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_7C1D345391824DF6BDCCE0AA7A0D12C7}}
          #subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          package: site


